export enum NotificationType {
  JOB_RECOMMENDATION = 'JOB_RECOMMENDATION',
  APPLICATION_UPDATE = 'APPLICATION_UPDATE',
  INTERVIEW_REMINDER = 'INTERVIEW_REMINDER',
  OFFER_UPDATE = 'OFFER_UPDATE',
  MESSAGE = 'MESSAGE',
  SYSTEM = 'SYSTEM',
}
